### ISSUE TITLE
Unknown command `switch`

### ISSUE THREAD

**Issue by darmie** [lix-pm/switchx#15]
I tried to switch versions of haxe by running `switchx switch 3.4.3` it didn't work. I am getting this error

`unknown command switch`

**Comment by benmerckx** [comment]
The `switch` command was renamed to `use` but it's not reflected in the docs it seems. If you run `switchx` without a command you'll get an up to date list of commands.

**Comment by back2dos** [comment]
What Ben said. Updated the doc ;)
