### ISSUE TITLE
Install as first command

### ISSUE THREAD

**Issue by benmerckx** [lix-pm/switchx#3]
I know it says to run `switchx` before using so this might be a non-issue. If you do forget and run a command it will run the default "It seems you're running switchx for the first time..." but will not continue to execute the command you entered. Let's say someone (me) forgets and runs `switchx install`, that will get you:
```
It seems you're running switchx for the first time.
Please wait for basic setup to finish ...
Looking up Haxe version "stable"
  Resolved to official release 3.4.0. Downloading ...
  ... download complete!
Now using official release 3.4.0
```
But I defined a different version in ".haxerc" :)

**Comment by back2dos** [comment]
Yeah, this is definitely weird, in particular because it works as it should on Windows but not on Linux. Probably some path gets messed up.
