### ISSUE TITLE
Haxe 3.4.1+

### ISSUE THREAD

**Issue by benmerckx** [lix-pm/switchx#6]
Since 3.4.1 the windows binary downloads are no longer packaged with a single root folder (eg 'haxe-3.4.0') but contain all files in the root of the zip. Installing 3.4.1 or 3.4.2 therefore causes the std folder to get unpacked in the installation dir. Didn't check other platforms, but they could possibly be affected as well.

**Comment by back2dos** [comment]
I settled for seeking the root (by looking for the first directory with more than one entry) rather than stripping a hardcoded number of path components. We'll see how long that works ^^
